"""remove_matriculas

Revision ID: 1533dbfe5a69
Revises: 90b1a03532fc
Create Date: 2025-12-23 13:02:54.249433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1533dbfe5a69'
down_revision: Union[str, Sequence[str], None] = '90b1a03532fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('carregamentos_matricula_rural_id_fkey'), 'carregamentos', type_='foreignkey')
    op.drop_column('carregamentos', 'matricula_rural_id')
    op.drop_column('carregamentos', 'matricula_codigo_snapshot')
    op.drop_table('matriculas_rurais')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carregamentos', sa.Column('matricula_rural_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('carregamentos', sa.Column('matricula_codigo_snapshot', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('carregamentos_matricula_rural_id_fkey'), 'carregamentos', 'matriculas_rurais', ['matricula_rural_id'], ['id'])
    op.create_table('matriculas_rurais',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=160), autoincrement=False, nullable=False),
    sa.Column('area_hectares', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('farm_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ativa', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], name=op.f('matriculas_rurais_farm_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('matriculas_rurais_pkey')),
    sa.UniqueConstraint('farm_id', 'codigo', name=op.f('uq_farm_matricula_codigo'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
