"""add_fields_and_variety

Revision ID: 3737a5ea9763
Revises: 1533dbfe5a69
Create Date: 2025-12-23 14:40:23.636529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3737a5ea9763'
down_revision: Union[str, Sequence[str], None] = '1533dbfe5a69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carregamentos', sa.Column('variety', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carregamentos', 'variety')
    # ### end Alembic commands ###
