"""update_carregamento_and_add_armazem

Revision ID: 8f87d09c91cf
Revises: 9e009859464c
Create Date: 2025-12-04 20:22:39.680498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f87d09c91cf'
down_revision: Union[str, Sequence[str], None] = '9e009859464c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    
    # 1. Update Data (Migration of existing values)
    bind.execute(sa.text("UPDATE carregamentos SET type = 'interno' WHERE type = 'INTERNAL'"))
    bind.execute(sa.text("UPDATE carregamentos SET type = 'remessa' WHERE type = 'EXTERNAL'"))
    
    # 2. Create Enum safely
    enum_obj = sa.Enum('interno', 'remessa', 'venda', name='tipocarregamento')
    enum_obj.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('armazens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('umidade_padrao', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fator_umidade', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('impurezas_padrao', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('eh_proprio', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('carregamentos', sa.Column('peso_estimado_kg', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('carregamentos', sa.Column('peso_bruto_kg', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('carregamentos', sa.Column('tara_kg', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('carregamentos', sa.Column('peso_liquido_kg', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('carregamentos', sa.Column('umidade_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('carregamentos', sa.Column('impurezas_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('carregamentos', sa.Column('peso_com_desconto_fazenda', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('carregamentos', sa.Column('peso_com_desconto_armazem', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('carregamentos', sa.Column('peso_recebido_final_kg', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('carregamentos', sa.Column('armazem_destino_id', sa.UUID(), nullable=True))
    
    # Alter column with explicit casting
    op.alter_column('carregamentos', 'type',
               existing_type=sa.VARCHAR(length=20),
               type_=enum_obj,
               existing_nullable=False,
               postgresql_using="type::tipocarregamento")
               
    op.create_foreign_key(None, 'carregamentos', 'armazens', ['armazem_destino_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'carregamentos', type_='foreignkey')
    op.alter_column('carregamentos', 'type',
               existing_type=sa.Enum('interno', 'remessa', 'venda', name='tipocarregamento'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('carregamentos', 'armazem_destino_id')
    op.drop_column('carregamentos', 'peso_recebido_final_kg')
    op.drop_column('carregamentos', 'peso_com_desconto_armazem')
    op.drop_column('carregamentos', 'peso_com_desconto_fazenda')
    op.drop_column('carregamentos', 'impurezas_percent')
    op.drop_column('carregamentos', 'umidade_percent')
    op.drop_column('carregamentos', 'peso_liquido_kg')
    op.drop_column('carregamentos', 'tara_kg')
    op.drop_column('carregamentos', 'peso_bruto_kg')
    op.drop_column('carregamentos', 'peso_estimado_kg')
    op.drop_table('armazens')
    # ### end Alembic commands ###
