"""Add weighing configuration columns

Revision ID: 90b1a03532fc
Revises: bfcac3c60f00
Create Date: 2025-12-22 11:11:26.366447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90b1a03532fc'
down_revision: Union[str, Sequence[str], None] = 'bfcac3c60f00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carregamentos', sa.Column('umidade_padrao', sa.Numeric(precision=4, scale=2), nullable=False, server_default='14.00'))
    op.add_column('carregamentos', sa.Column('fator_umidade', sa.Numeric(precision=4, scale=2), nullable=False, server_default='1.50'))
    op.add_column('carregamentos', sa.Column('impurezas_padrao', sa.Numeric(precision=4, scale=2), nullable=False, server_default='1.00'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carregamentos', 'impurezas_padrao')
    op.drop_column('carregamentos', 'fator_umidade')
    op.drop_column('carregamentos', 'umidade_padrao')
    # ### end Alembic commands ###
