"""add_type_to_carregamentos

Revision ID: 9e009859464c
Revises: a8f1b50c055f
Create Date: 2025-12-03 08:57:51.651997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e009859464c'
down_revision: Union[str, Sequence[str], None] = 'a8f1b50c055f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carregamentos', sa.Column('type', sa.String(length=20), nullable=False))
    op.drop_constraint(op.f('groups_owner_id_fkey'), 'groups', type_='foreignkey')
    op.create_foreign_key(None, 'groups', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.create_foreign_key(op.f('groups_owner_id_fkey'), 'groups', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.drop_column('carregamentos', 'type')
    # ### end Alembic commands ###
