"""Add company discount fields

Revision ID: a252deb2e836
Revises: 8f87d09c91cf
Create Date: 2025-12-11 12:04:38.221061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a252deb2e836'
down_revision: Union[str, Sequence[str], None] = '8f87d09c91cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carregamentos', sa.Column('umidade_empresa_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('carregamentos', sa.Column('impurezas_empresa_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('carregamentos', sa.Column('peso_com_desconto_empresa', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carregamentos', 'peso_com_desconto_empresa')
    op.drop_column('carregamentos', 'impurezas_empresa_percent')
    op.drop_column('carregamentos', 'umidade_empresa_percent')
    # ### end Alembic commands ###
