"""add_group_token_and_farm_defaults

Revision ID: b7155acce9a6
Revises: ce2ad9ad3437
Create Date: 2025-12-11 19:51:29.119274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7155acce9a6'
down_revision: Union[str, Sequence[str], None] = 'ce2ad9ad3437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farms', sa.Column('default_cfop', sa.String(length=5), nullable=True))
    op.add_column('farms', sa.Column('default_natureza_operacao', sa.String(length=160), nullable=True))
    op.add_column('groups', sa.Column('focus_nfe_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'focus_nfe_token')
    op.drop_column('farms', 'default_natureza_operacao')
    op.drop_column('farms', 'default_cfop')
    # ### end Alembic commands ###
