"""Add driver_document to Carregamento

Revision ID: bb884eff97bd
Revises: b7155acce9a6
Create Date: 2025-12-20 18:22:25.421848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb884eff97bd'
down_revision: Union[str, Sequence[str], None] = 'b7155acce9a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carregamentos', sa.Column('driver_document', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carregamentos', 'driver_document')
    # ### end Alembic commands ###
