"""Add Matricula Rural and Link to Carregamento

Revision ID: bfcac3c60f00
Revises: bb884eff97bd
Create Date: 2025-12-20 18:46:36.800999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfcac3c60f00'
down_revision: Union[str, Sequence[str], None] = 'bb884eff97bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matriculas_rurais',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=160), nullable=False),
    sa.Column('area_hectares', sa.Float(), nullable=True),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'codigo', name='uq_farm_matricula_codigo')
    )
    op.add_column('carregamentos', sa.Column('matricula_rural_id', sa.Integer(), nullable=True))
    op.add_column('carregamentos', sa.Column('matricula_codigo_snapshot', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'carregamentos', 'matriculas_rurais', ['matricula_rural_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'carregamentos', type_='foreignkey')
    op.drop_column('carregamentos', 'matricula_codigo_snapshot')
    op.drop_column('carregamentos', 'matricula_rural_id')
    op.drop_table('matriculas_rurais')
    # ### end Alembic commands ###
