"""add_nfe_fields_dynamic

Revision ID: ce2ad9ad3437
Revises: a252deb2e836
Create Date: 2025-12-11 18:14:01.956024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce2ad9ad3437'
down_revision: Union[str, Sequence[str], None] = 'a252deb2e836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('armazens', sa.Column('inscricao_estadual', sa.String(length=20), nullable=True))
    op.add_column('armazens', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('armazens', sa.Column('telefone', sa.String(length=20), nullable=True))
    op.add_column('armazens', sa.Column('logradouro', sa.String(length=200), nullable=True))
    op.add_column('armazens', sa.Column('numero', sa.String(length=20), nullable=True))
    op.add_column('armazens', sa.Column('bairro', sa.String(length=100), nullable=True))
    op.add_column('armazens', sa.Column('municipio', sa.String(length=100), nullable=True))
    op.add_column('armazens', sa.Column('uf', sa.String(length=2), nullable=True))
    op.add_column('armazens', sa.Column('cep', sa.String(length=10), nullable=True))
    op.add_column('carregamentos', sa.Column('cfop', sa.String(length=5), nullable=True))
    op.add_column('carregamentos', sa.Column('natureza_operacao', sa.String(length=160), nullable=True))
    op.add_column('carregamentos', sa.Column('ncm', sa.String(length=10), nullable=True))
    op.add_column('carregamentos', sa.Column('valor_unitario', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('farms', sa.Column('cnpj', sa.String(length=20), nullable=True))
    op.add_column('farms', sa.Column('inscricao_estadual', sa.String(length=20), nullable=True))
    op.add_column('farms', sa.Column('telefone', sa.String(length=20), nullable=True))
    op.add_column('farms', sa.Column('logradouro', sa.String(length=200), nullable=True))
    op.add_column('farms', sa.Column('numero', sa.String(length=20), nullable=True))
    op.add_column('farms', sa.Column('bairro', sa.String(length=100), nullable=True))
    op.add_column('farms', sa.Column('municipio', sa.String(length=100), nullable=True))
    op.add_column('farms', sa.Column('uf', sa.String(length=2), nullable=True))
    op.add_column('farms', sa.Column('cep', sa.String(length=10), nullable=True))
    op.add_column('farms', sa.Column('regime_tributario', sa.String(length=1), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farms', 'regime_tributario')
    op.drop_column('farms', 'cep')
    op.drop_column('farms', 'uf')
    op.drop_column('farms', 'municipio')
    op.drop_column('farms', 'bairro')
    op.drop_column('farms', 'numero')
    op.drop_column('farms', 'logradouro')
    op.drop_column('farms', 'telefone')
    op.drop_column('farms', 'inscricao_estadual')
    op.drop_column('farms', 'cnpj')
    op.drop_column('carregamentos', 'valor_unitario')
    op.drop_column('carregamentos', 'ncm')
    op.drop_column('carregamentos', 'natureza_operacao')
    op.drop_column('carregamentos', 'cfop')
    op.drop_column('armazens', 'cep')
    op.drop_column('armazens', 'uf')
    op.drop_column('armazens', 'municipio')
    op.drop_column('armazens', 'bairro')
    op.drop_column('armazens', 'numero')
    op.drop_column('armazens', 'logradouro')
    op.drop_column('armazens', 'telefone')
    op.drop_column('armazens', 'email')
    op.drop_column('armazens', 'inscricao_estadual')
    # ### end Alembic commands ###
