import type { User, UserRole } from './types'

export const USER_ROLES: { value: UserRole; label: string }[] = [
  { value: 'funcionario-comum', label: 'Funcionário Comum' },
  { value: 'operador-maquinas', label: 'Operador de Máquinas' },
  { value: 'controle-financeiro', label: 'Controle Financeiro' },
  { value: 'gerente', label: 'Gerente' },
  { value: 'administrador-local', label: 'Administrador Local' },
  { value: 'desativado', label: 'Desativado' },
]

export const SETORES = [
  'Produção',
  'Administração',
  'Financeiro',
  'Logística',
  'Manutenção',
  'Recursos Humanos',
  'Qualidade',
]

export const FAZENDAS = [
  'Fazenda Imperial',
  'Fazenda São João',
  'Fazenda Santa Maria',
  'Fazenda Nova Esperança',
]

export const INITIAL_USERS: User[] = [
  {
    id: 'user-1',
    nome: 'João Silva',
    email: 'joao.silva@fazenda.com',
    cargo: 'funcionario-comum',
    setor: 'Produção',
    status: 'ativo',
    fazenda: 'Fazenda Imperial',
    avatar: '👨‍🌾',
    dataCriacao: '2024-01-15',
    ultimoAcesso: '2024-12-20',
  },
  {
    id: 'user-2',
    nome: 'Maria Santos',
    email: 'maria.santos@fazenda.com',
    cargo: 'operador-maquinas',
    setor: 'Produção',
    status: 'ativo',
    fazenda: 'Fazenda Imperial',
    avatar: '👩‍🔧',
    dataCriacao: '2024-02-10',
    ultimoAcesso: '2024-12-20',
  },
  {
    id: 'user-3',
    nome: 'Pedro Oliveira',
    email: 'pedro.oliveira@fazenda.com',
    cargo: 'controle-financeiro',
    setor: 'Financeiro',
    status: 'ativo',
    fazenda: 'Fazenda Imperial',
    avatar: '👨‍💼',
    dataCriacao: '2024-01-20',
    ultimoAcesso: '2024-12-19',
  },
  {
    id: 'user-4',
    nome: 'Ana Costa',
    email: 'ana.costa@fazenda.com',
    cargo: 'gerente',
    setor: 'Administração',
    status: 'ativo',
    fazenda: 'Fazenda Imperial',
    avatar: '👩‍💼',
    dataCriacao: '2023-12-01',
    ultimoAcesso: '2024-12-20',
  },
  {
    id: 'user-5',
    nome: 'Carlos Mendes',
    email: 'carlos.mendes@fazenda.com',
    cargo: 'administrador-local',
    setor: 'Administração',
    status: 'ativo',
    fazenda: 'Fazenda Imperial',
    avatar: '👨‍💻',
    dataCriacao: '2023-11-15',
    ultimoAcesso: '2024-12-20',
  },
  {
    id: 'user-6',
    nome: 'Fernanda Lima',
    email: 'fernanda.lima@fazenda.com',
    cargo: 'operador-maquinas',
    setor: 'Produção',
    status: 'ativo',
    fazenda: 'Fazenda São João',
    avatar: '👩‍🚜',
    dataCriacao: '2024-03-05',
    ultimoAcesso: '2024-12-19',
  },
  {
    id: 'user-7',
    nome: 'Roberto Alves',
    email: 'roberto.alves@fazenda.com',
    cargo: 'funcionario-comum',
    setor: 'Produção',
    status: 'inativo',
    fazenda: 'Fazenda Imperial',
    avatar: '👨‍🌾',
    dataCriacao: '2024-05-10',
    ultimoAcesso: '2024-11-15',
  },
  {
    id: 'user-8',
    nome: 'Juliana Ferreira',
    email: 'juliana.ferreira@fazenda.com',
    cargo: 'controle-financeiro',
    setor: 'Financeiro',
    status: 'ativo',
    fazenda: 'Fazenda Santa Maria',
    avatar: '👩‍💼',
    dataCriacao: '2024-04-20',
    ultimoAcesso: '2024-12-20',
  },
]

